# Initializing and seeding
defaults:
  - BaseRecipe
  - _self_
initial_runtime_state:
  seed: 42
# Defining blueprints
blueprints:
  measurement_techniques:
    TopCamInAir:
      measurement_technique_prototype_name: plane_topCam_fog
      measurement_volume_material_prototype_name: vacuum
      background_material_prototype_name: plain
  particles:
    Bead:
      geometry_prototype_name: sphere
      material_prototype_name: plain
      parent: MeasurementVolume
      number: 40
# Physical boundary conditions
process_conditions:
  feature_variabilities:
    InitialParticleLocation:
      feature_name: location
      variability:
        _target_: $builtins.UniformlyRandomLocationInMeasurementVolume
    ParticleDimension:
      feature_name: dimensions
      variability:
        _target_: $builtins.UniformDistribution3dHomogeneous
        location: 3.3
        scale: 1.4
    RenderingResolutionPercentage:
      feature_name: resolution_percentage
      variability:
        _target_: $builtins.Constant
        value: 25
    CyclesSamples:
      feature_name: cycles_samples
      variability:
        _target_: $builtins.Constant
        value: 64 # during tutorial
        # value: 2048 # only for final render
    BackgroundColor:
      feature_name: color
      variability:
        _target_: $plugins.official.ConstantHsvColorAsRgb
        hue: 0.15
        saturation: 0.35
    PinkColor:
      feature_name: color
      variability:
        _target_: $plugins.official.ConstantHsvColorAsRgb
        hue: 0.95
        saturation: 0.85
# Procedural steps of synthetization chain
synth_chain:
  feature_generation_steps:
    - _target_: $builtins.InvokeBlueprints
      affected_set_name: AllMeasurementTechniqueBlueprints
    - _target_: $builtins.InvokeBlueprints
      affected_set_name: AllParticleBlueprints
    - _target_: $builtins.TriggerFeatureUpdate
      feature_variability_name: InitialParticleLocation
      affected_set_name: AllParticles
    - _target_: $builtins.TriggerFeatureUpdate
      feature_variability_name: ParticleDimension
      affected_set_name: AllParticles
    - _target_: $builtins.RelaxCollisions
      affected_set_name: AllParticles
      num_frames: 20
      collision_shape: SPHERE
    - _target_: $builtins.RelaxCollisions
      affected_set_name: AllParticles
      use_gravity: True
      damping: 0.07
      friction: 0.4
      restitution: 0.1
      collision_margin: 0.5
      num_frames: 150
      collision_shape: CONVEX_HULL
    - _target_: $builtins.TriggerFeatureUpdate
      feature_variability_name: BackgroundColor
      affected_set_name: AllMeasurementTechniques
    - _target_: $builtins.TriggerFeatureUpdate
      feature_variability_name: PinkColor
      affected_set_name: AllParticles
    - _target_: $builtins.TriggerFeatureUpdate
      feature_variability_name: RenderingResolutionPercentage
      affected_set_name: AllMeasurementTechniques
    - _target_: $builtins.TriggerFeatureUpdate
      feature_variability_name: CyclesSamples
      affected_set_name: AllMeasurementTechniques
  rendering_steps:
    - _target_: $builtins.RenderParticlesTogether
      rendering_mode: real
      do_save_features: True