# Defining blueprints
blueprints:
  measurement_techniques:
    TopCamInAir:
      measurement_technique_prototype_name: woodTable_sideCam
      measurement_volume_material_prototype_name: vacuum
      background_material_prototype_name: wood
  particles:
    Bead:
      geometry_prototype_name: ellipsoid
      material_prototype_name: colored_subtle
      parent: MeasurementVolume
      number: 200
      # number: 500
# Physical boundary conditions
process_conditions:
  feature_variabilities:
    CameraNearTable: # can be thrown out after first comparison render
      feature_name: cam_location_z
      variability:
        _target_: $builtins.Constant
        value: -35.0
    ShowGlass:
      feature_name: glass_hide
      variability:
        _target_: $builtins.Constant
        value: False
    CollisionGlass:
      feature_name: glass_collision
      variability:
        _target_: $builtins.Constant
        value: True
    CameraRotation:
      feature_name: cam_rotation
      variability:
        _target_: $builtins.UniformDistributionNdHomogeneous
        location: -0.0523598775598299
        scale: 0.10471975511966               
        num_dimensions: 1
    CameraAltitude:
      feature_name: cam_altitude
      variability:
        _target_: $builtins.UniformDistributionNdHomogeneous
        location: -0.15707963267949
        scale: 0.314159265358979
        num_dimensions: 1
    CameraAzimuth:
      feature_name: cam_azimuth
      variability:
        _target_: $builtins.UniformDistributionNdHomogeneous
        location: 0.0
        scale: 6.28318530717959
        num_dimensions: 1
    GlassRotation:
      feature_name: glass_rotation
      variability:
        _target_: $builtins.UniformDistributionNdHomogeneous
        location: 0.0
        scale: 0.698131700797732
        num_dimensions: 1
    TableRotation:
      feature_name: table_rotation
      variability:
        _target_: $builtins.UniformDistributionNdHomogeneous
        location: 0.0
        scale: 6.28318530717959
        num_dimensions: 1
    WoodTexture:
      feature_name: texture_seed
      variability:
        _target_: $builtins.UniformDistributionNdHomogeneous
        location: 0
        scale: 1000
        num_dimensions: 1
